blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):

    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержимое')
    preview_image = models.ImageField(upload_to='blog/', verbose_name='Превью', null=True, blank=True)
    publication_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        if self.object.views_count == 100:
            subject = 'Поздравляем с достижением 100 просмотров!'
            message = 'Ваша статья достигла 100 просмотров. Поздравляем!'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = ['russsssanov@yandex.ru']

            send_mail(subject, message, from_email, recipient_list)

        return self.object



class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview_image', )
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview_image',)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                      <p>Хотите удалить статью "{{ object.title}}"?</p>
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                      <a href="{% url 'blog:list' %}" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="col-6">
                        {% if object.preview_image %}
                        <img src="/media/{{object.preview_image}}"/>
                        <br>
                        {% endif %}
                        <br>
                        <h3 class="card-title">
                            Статья "{{ object.title|title }}"</h3>
                        <div class="card-body">
                            <p>
                                {{ object.content }}
                            </p>
                        </div>
                    </div>
                    <div class="card-footer">Просмотры: {{ object.views_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>

{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object|title }}
            </p>
             <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'blog:view' object.pk %}" class="btn btn-sm btn-outline-secondary mr-2">View</a>
                    <a href="{% url 'blog:edit' object.pk %}" class="btn btn-sm btn-outline-secondary mr-2">Edit</a>
                    <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-outline-danger mr-2">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}