blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, CustomPasswordResetView, \
    CustomPasswordResetCompleteView, CustomPasswordResetConfirmView, CustomPasswordResetDoneView


app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView .as_view(), name='logout'),
    path('register/', RegisterView .as_view(), name='register'),
    path('profile/', ProfileView .as_view(), name='profile'),
    path('confirm_email/<str:key>/', verify_email, name='verify_email'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):  # переопределяем модель для пользователя

    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)

    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', blank=True, null=True)
    country = models.CharField(max_length=100, verbose_name='Страна', blank=True, null=True)

    verify_key = models.CharField(max_length=255, null=True, blank=True, verbose_name='Ключ верификации')
    is_verified = models.BooleanField(default=False, verbose_name='верифицирован')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        db_table = 'users'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):  # форма для регистрации

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):  # форма для редактирования профиля

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
import secrets

from users.forms import UserRegisterForm, UserProfileForm
# Create your views here.
from users.models import User
from users.services import send_email_for_verify

from django.contrib.auth.views import PasswordResetView, PasswordResetCompleteView, PasswordResetDoneView, PasswordResetConfirmView

# Функционал контроллеров LoginView и LogoutView не меняем


class RegisterView(CreateView):  # контроллер доя регистрации пользователя
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            verify_key = secrets.token_urlsafe(32)  # генерируем случайный ключ

            user = form.save(commit=False)
            user.verify_key = verify_key  # сохраняем ключ к пользователю
            user.save()  # сохраняем пользователя с ключом

            current_site = get_current_site(self.request)  # получаем сайт для формирования ссылки
            verify_link = f"http://{current_site.domain}{reverse('users:verify_email', args=[verify_key])}"
            send_email_for_verify(user, verify_link)  # отправляем сообщение
            return render(self.request, 'users/verify_email.html')  # перенаправляем на страницу с сообщением о проверке почты

        return super().form_valid(form)


class ProfileView(UpdateView):  # контроллер для изменения пользователя
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('catalog:home')

    def get_object(self, queryset=None):
        return self.request.user


def verify_email(request, key):   # контроллер для верификации пользователя

    user = User.objects.filter(verify_key=key).first()   # получаем пользователя по ключу
    if user:    # проверяем, существует ли такой пользователь
        user.is_verified = True
        user.save()
        # Перенаправление на страницу с сообщением об успешной верификации
        return render(request, 'users/verification_success.html')
    else:
        # Перенаправление на страницу с сообщением об ошибке
        return render(request, 'users/verification_error.html')


class CustomPasswordResetView(PasswordResetView):   # контроллер для сброса пароля
    template_name = 'users/registration/password_reset_form.html'
    email_template_name = 'users/registration/password_reset_email.html'
    success_url = reverse_lazy("users:password_reset_done")


class CustomPasswordResetDoneView(PasswordResetDoneView):  # контроллер для успешной страницы сброса пароля.
    template_name = 'users/registration/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):  # контроллер для подтверждения сброса пароля.
    template_name = 'users/registration/password_reset_confirm.html'
    success_url = reverse_lazy("users:password_reset_complete")


class CustomPasswordResetCompleteView(PasswordResetCompleteView):  # контроллер для страницы успешного завершения сброса пароля.
    template_name = 'users/registration/password_reset_complete.html'

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">
                Вход
            </h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="col-3">

                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">Войти</button>
            </form>
        </div>
        <div class="card-footer">
            <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">
                Регистрация
            </h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="col-3">

                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">
                Профиль
            </h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="col-3">

                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">Сохранить</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>

{% endblock %}

users/templates/users/verification_error.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Ошибка подтверждения email</div>

                <div class="card-body">
                    <p>Произошла ошибка при подтверждении вашего email адреса. Пожалуйста, проверьте правильность ключа подтверждения или <a href="{% url 'users:resend_verification' %}">запросите новое письмо</a>.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/verification_success.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Email подтвержден</div>

                <div class="card-body">
                    <p>Ваш email адрес успешно подтвержден. Теперь вы можете войти в свой аккаунт.</p>
                    <p><a href="{% url 'users:login' %}">Войти</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">Подтвердите Email</div>

                <div class="card-body">
                    <p>На вашу почту было отправлено письмо с инструкциями по подтверждению вашего email адреса.</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}