blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import get_contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', get_contacts, name='contacts'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('create_product/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User

# Константа для обозначения необязательных полей
NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена за покупку')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    change_date = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', default=1)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Version(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.CharField(max_length=150, verbose_name='Номер версии')
    version_title = models.CharField(max_length=150, verbose_name='Название версии')
    current_version = models.BooleanField(default=False, verbose_name='Текущая версия')

    def __str__(self):
        return f'Версия {self.version_number} {self.version_title}'

    def save(self, *args, **kwargs):
        if self.current_version:
            Version.objects.filter(product=self.product, current_version=True).update(current_version=False)
        super(Version, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        db_table = 'versions'

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class VersionForm(forms.ModelForm):

    current_version = forms.BooleanField(
        required=False,
        label='Активная версия',
        widget=forms.CheckboxInput(attrs={'class': 'checkbox-input'}),
    )

    class Meta:
        model = Version
        fields = ('version_number', 'version_title', 'current_version',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['current_version'].widget.attrs['class'] = 'checkbox-left'


class ProductForm(forms.ModelForm):

    FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа',
                       'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'category', 'price',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')

        for word in self.FORBIDDEN_WORDS:
            if word == cleaned_data.lower() or word in cleaned_data.lower():
                raise forms.ValidationError(f'Название содержит запрещенное слово {word}')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')

        for word in self.FORBIDDEN_WORDS:
            if word == cleaned_data.lower() or word in cleaned_data.lower():
                raise forms.ValidationError(f'Описание содержит запрещенное слово "{word}"')
        return cleaned_data

catalog/views.py
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from catalog.models import Product, Version
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm


class VerificationRequiredMixin:
    """Миксин для предварительной проверки подтверждения пользователя"""

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_verified):
            return HttpResponseForbidden("Доступ запрещен")
        return super().dispatch(request, *args, **kwargs)


class ProductListView(ListView):
    """Контроллер для отображения списка товаров"""
    model = Product
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)

        for object in context['products']:
            try:
                active_version = Version.objects.get(product=object, current_version=True)
                object.current_version = active_version
            except Version.DoesNotExist:
                object.current_version = None

        return context


def get_contacts(request):
    """Контроллер, который отвечает за отображение контактной информации и обрабатывает POST запрос"""
    context = {
        'title': 'Контакты'
    }

    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}\n'
              f'Телефон: {phone}\n'
              f'Сообщение: {message}')

    return render(request, 'catalog/contacts.html', context)


class ProductDetailView(DetailView):
    """Контроллер для отображения страницы с товаром"""
    model = Product


class ProductCreateView(VerificationRequiredMixin, CreateView):
    """Контроллер для создания нового товара"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')


class ProductUpdateView(VerificationRequiredMixin, UpdateView):
    """Контроллер для редактирования товара"""
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:edit_product', args=[self.kwargs['pk']])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(VerificationRequiredMixin, DeleteView):
    """Контроллер для удаления товара"""
    model = Product
    fields = ('title', 'description', 'image', 'category', 'price')
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white mb-4">О нас</h4>
                    <p class="text-muted">Магазин "Skystore" предоставляет широкий ассортимент продуктов для вашего
                        комфорта и удовольствия. Наша цель - сделать вашу покупку максимально приятной и удобной,
                        предоставив качественные товары по доступным ценам. Мы гордимся тем, что помогаем нашим клиентам
                        находить то, что им действительно нужно.</p>
                </div>
               {% include 'catalog/includes/inc_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center"></a>
            <h1 style="color: white; font-size: 24px;">SKYSTORE</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">
    {% url 'catalog:home' as url_catalog_home %}
    {% if request.path == url_catalog_home %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Каталог</h1>
        </div>
    </section>
    {% endif %}
    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Наверх</a>
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
        <p><a href="../../">На главную</a></p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('.navbar-toggler').on('click', function () {
            $('#navbarHeader').toggleClass('show');
        });
    });
</script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="contact-container">
        <div class="contact-info">
            <h1 class="display-4 text-center">Свяжитесь с нами</h1>
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Страна</td>
                    <td>USA</td>
                </tr>
                <tr>
                    <td class="w-25">ИНН</td>
                    <td>91-1144442</td>
                </tr>
                <tr>
                    <td class="w-25">Адрес</td>
                    <td>Redmond, WA, 98052-6399</td>
                </tr>
            </table>
        </div>
        <div class="contact-form">
            <h4 class="my-0 font-weight-normal text-center">Оставьте ваше сообщение</h4>
            <form method="post" action="" class="form-floating">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name">Имя</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                </div>
                <div class="mb-3">
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                </div>
                <div class="mb-3">
                    <label for="message">Сообщение</label>
                    <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow d-flex flex-column">
            <img class="card-img-top"
                 src="{{ object.image|mediapath }}"
                 alt="Card image cap">
            <div class="card-body d-flex flex-column">
                <p class="card-text text-center">{{ object.title }}</p>
                <div class="text-center">
                    <p class="card-text">{{ object.description|slice:":100" }}</p>
                    <a href="{% url 'catalog:product_detail' object.id %}"
                       class="btn btn-sm btn-outline-secondary text-center mx-auto">Подробнее о товаре</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img class="card-img-top"
                 src="{% mediapath object.image %}"
                 alt="Card image cap">
            <h1>{{ object.title|title }}</h1>
            <p class="lead">{{ object.description }}</p>
            <p class="text-muted">Цена: {{ object.price }} руб.</p>
            <button class="btn btn-primary">Купить</button>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                      <p>Хотите удалить продукт "{{ object.title}}"?</p>
                        <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                      <a href="{% url 'catalog:home' %}" class="btn btn-outline-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img class="card-img-top"
                 src="{% mediapath object.image %}"
                 alt="Card image cap">
            <h1>{{ object.title|title }}</h1>
            <p class="lead">{{ object.description }}</p>
            <p class="text-muted">Цена: {{ object.price }} руб.</p>
            <button class="btn btn-primary">Купить</button>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header text-center">
                {% if object %}
                <h2>Изменение продукта</h2>
                {% else %}
                <h2>Добавление продукта</h2>
                {% endif %}
            </div>
            <br>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Версия
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p}}
                {% endfor %}
            </div>
        </div>
    </div>
</form>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>

</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow d-flex flex-column">
            <img class="card-img-top"
                 src="{{ object.image|mediapath }}"
                 alt="Card image cap">
            <div class="card-body d-flex flex-column">
                <p class="card-text text-center">{{ object.title }}</p>
                <div class="text-center">
                    <p class="card-text">{{ object.description|slice:":100" }}</p>
                    {% if object.current_version  %}
                    <p class="card-text">
                        Текущая версия: {{ object.current_version.version_number }} - {{ object.current_version.version_title }}
                    </p>
                    {% endif %}
                    <a href="{% url 'catalog:view_product' object.pk %}"
                       class="btn btn-sm btn-outline-secondary text-center mx-auto btn-details">Подробнее</a>
                    <a href="{% url 'catalog:edit_product' object.pk %}"
                       class="btn btn-sm btn-outline-secondary text-center mx-auto btn-edit">Изменить</a>
                    <a href="{% url 'catalog:delete_product' object.pk %}"
                       class="btn btn-sm btn-outline-secondary text-center mx-auto btn-delete">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}